### ISSUE TITLE
Read/write mounted volumes?

### ISSUE THREAD

**Issue by darribas** [sunu/jupyter-remote-qgis-proxy#1]
[I'm not sure this is the right repo, but I didn't find and Issues section over at `sunu/nasa-qgis-image`]

This project is _fantastic_! Thank you so much for this, I'd been thinking something like this should be possible for a while but hadn't seen it.

Now, my question: is there a reason why I'm getting the mounted volume on the container non-readable/writeable?

Following [your guidelines](https://github.com/sunu/jupyter-remote-qgis-proxy?tab=readme-ov-file#usage), I can run correctly:

```
docker run -it -p 8888:8888 --security-opt seccomp=unconfined qgis
```

But if I try something like:

```
docker run -it -v /path/to/host/folder:/home/jovyan/work -p 8888:8888 --security-opt seccomp=unconfined qgis
```

The `work` folder appears but the files from the host can't be accessed. Is there a reason for that? I work often with the Jupyter image this is built on top of and have no issue doing what I'm trying here. Is there a workaround? Any tips and guidance would be most appreciated.

**Comment by sunu** [comment]
Hi @darribas, thanks a lot for your kind words!

jupyter-remote-qgis-proxy is now a part of the upstream [nasa-qgis-image](https://github.com/2i2c-org/nasa-qgis-image) repo. I have updated the documentation to reflect that.

Regarding the issue you mentioned, I tried to reproduce it using both a prebuilt image and a locally built one with the following commands:
For the prebuilt image:
```
docker run -it -v /tmp/qgis-test:/home/jovyan/work -p 8888:8888 --security-opt seccomp=unconfined quay.io/2i2c/nasa-qgis-image:ce0b7c7f33ea
```

For the locally built image:
```
docker run -it -v /tmp/qgis-test:/home/jovyan/work -p 8888:8888 --security-opt seccomp=unconfined qgis
```

Interestingly, I wasn't able to reproduce the problem. In both cases, I could access `~/work` in read/write mode without any issues - I was able to access files from the host and write new files successfully from within the Jupyter interface.

Can you please try with a prebuilt image and let me know if you're still experiencing this issue? I'd be happy to investigate further and see if we can identify what's causing the problem.

**Comment by darribas** [comment]
Somehow I was doing something odd, but this now seems to work just as expected. Thanks! Closing now as resolved.

Ps. do you think there’s room to implement opening QGIS in full-screen mode? If you’re focused on deploying the app rather than the full environment, it abstracts away the fact that there is a full desktop env behind it.

Ps2. Do you know if there’s an (easy) way to resize the desktop window so it takes up the entire browser? Unless I’m on exactly the dimensions set, there’s a grey area on both sides. It’s really not a big deal, but if you’re running this on a small screen (e.g., iPad) everything counts :-)

[Apologies for the barrage of questions…]

**Comment by sunu** [comment]
@darribas Good to know that you got it working!

To answer the questions:

Technically, we can easily implement opening QGIS in full-screen mode by switching the `mainWindow().showMaximized()` call at https://github.com/sunu/jupyter-remote-qgis-proxy/blob/0939057836e98e7c656df6090bf18400c34537e5/jupyter_remote_qgis_proxy/qgis/scripts/maximize.py#L6 to `mainWindow().showFullScreen()`. But I'm not 100% sure if that's a better default choice for all users. May be we can make this behaviour customizable.

Resizing the desktop window so it takes up the entire browser is already implemented upstream in https://github.com/jupyterhub/jupyter-remote-desktop-proxy/pull/124. That improvement should be available in the QGIS image soon after the next version release of jupyter-remote-desktop-proxy.
